FROM golang:1.25.3-alpine

WORKDIR /app

# Install air for hot reload
RUN go install github.com/air-verse/air@latest

# Copy go mod files
COPY go.mod go.sum ./
RUN go mod download

# Copy the entire project
COPY . .

EXPOSE 8080 50057

# Use air for hot reload
CMD ["/go/bin/air", "-c", "./services/CartService/.air.toml"]